# Generated by Django 5.1.2 on 2024-10-31 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='global_markup',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved_by_admin', 'Approved by Admin'), ('approved_by_user', 'Approved by User'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('markup_percentage', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='projects.project')),
            ],
        ),
    ]
