# Generated by Django 5.1.2 on 2024-11-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_project_created_at_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectelement',
            name='name',
            field=models.CharField(default='Hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Completed', 'Completed')], default='pending', max_length=20, null=True),
        ),
    ]
